accounts/urls.py
from django.urls import path
from . import views

app_name='accounts'

urlpatterns=[
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('<int:id>/update/', views.update, name='update'),
    path('<int:id>/delete/', views.delete, name='delete'),
    
    path('<int:id>/comments/create/', views.comment_create, name='comment_create'),
    path('<int:id>/comments/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
]

auth/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.
class User(AbstractUser):
    pass
    # article_set 장고가 자동으로 생성해주는 컬럼(ForeignKey)
    # comment_set 장고가 자동으로 생성해주는 컬럼(Foreignkey)

articles/models.py
from django.db import models
from accounts.models import User
from django.conf import settings
from django.contrib.auth import get_user_model
class Article(models.Model):
    title = models.CharField(max_length=40)
    content = models.TextField()

    # 유저 모델을 참조하는 경우
    # 1. 권장 x
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    # 2. 권장 -> settings.AUTH_USER_MODEL == 'accounts.User' 유지보수에 유리
    # user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # 3. 권장 -> auth에서 get_user_model 함수를 가져와 실행결과를 ForeignKey에 참조값으로 씀
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id = 장고가 자동으로 추가해주는 컬럼
    # comment_set = 장고가 자동으로 추가해주는 컬럼
class Comment(models.Model):
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # article_id = 장고가 자동으로 추가해주는 컬럼
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE)
    # user_id = 장고가 자동으로 추가해주는 컬럼

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import User

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields

class CustomAuthenticationForm(AuthenticationForm):
    pass

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    # title = forms.CharField(
    #     label='제목입니다.',
    #     widget=forms.TextInput(
    #         attrs={
    #             'class': 'form-control',
    #         }
    #     )
    # )
    # content = forms.CharField(
    #     label='내용입니다.',
    #     widget=forms.Textarea(
    #         attrs={
    #             'class': 'form-control',
    #         }
    #     )
        
    # )
    class Meta():
        model = Article
        # fields = '__all__'
        exclude = ('user', )

class CommentForm(forms.ModelForm):
    class Meta():
        model = Comment
        # fields = '__all__'
        exclude = ('article', 'user', )

accounts/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm, CustomAuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('articles:index')

    else:
        form = CustomUserCreationForm()
    context = {
        'form': form,
    }
    return render(request, 'signup.html', context)

def login(request):
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            # 로그인
            auth_login(request, form.get_user())

            next_url = request.GET.get('next')
            # http://127.0.0.1:8000/accounts/login/ => None
            # http://127.0.0.1:8000/accounts/login?next=/articles/create/ => /articles/create
            return redirect(next_url or 'articles:index')

    else:
        form = CustomAuthenticationForm()
    context = {
            'form': form,
    }
    return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('accounts:login')

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles
    }
    return render(request,'index.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    form = CommentForm()
    context= {
        'article': article,
        'form': form,
    }
    return render(request, 'detail.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save(commit=False)
            # 현재 로그인한 사람 정보를 넣어줌
            article.user = request.user
            article.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)

@login_required
def update(request, id):
    article = Article.objects.get(id=id)
    if request.user != article.user:
        return redirect('articles:detail', id=id)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', id=id)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)
    

@login_required
def delete(request, id):
    article = Article.objects.get(id=id)
    if request.user == article.user:
        article.delete()
        return redirect('articles:index')
    return redirect('articles:detail', id=id)

@login_required
def comment_create(request, id):
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.user = request.user
        comment.article_id = id
        comment.save()
    return redirect('articles:detail', id=id)

@login_required
def comment_delete(request, id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', id=id)
    

accounts/templates/login.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-primary">
    </form>
{% endblock %}

articles/templates/detail.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% block body %}
<a href="{% url 'articles:index' %}" class="d-flex justify-content-end">to list</a>
<div class="card">
    <div class="card-header d-flex justify-content-between">
        <span class="card-title">{{ article.title }}</span>
        <span class="card-subtitle mb-2 text-body-secondary">{{ article.user }}</span>
    </div>
    <div class="card-body">
        <p class="card-text">{{ article.content }}</p>
    </div>
    <div class="card-footer">
        {% if user == article.user %}
        <a href="{% url 'articles:update' id=article.id %}">update</a>
        <a href="{% url 'articles:delete' id=article.id %}">delete</a>
        {% endif %}
    </div>
</div>
<div>
    <h4>댓글</h4>
    <hr>
    <div>
        {% if user.is_authenticated %}
        <form action="{% url 'articles:comment_create' id=article.id %}" method="POST">
            {% csrf_token %}
            {% bootstrap_form form show_label=Flase %}
            <input type="submit" class="btn btn-primary">
        </form>
        {% endif %}
    </div>
    <div>
        {% for comment in article.comment_set.all %}
        <div class="alert alert-light">
            {{ comment.user }}:
            {{ comment.content }}
            {% if comment.user == user %}
                <a href="{% url 'articles:comment_delete' id=article.id comment_id=comment.id %}" class="d-flex">delete</a>
            {% endif %}
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}
{% load bootstrap5 %}

{% block body %}
    <form action="" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit">
    </form>
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
    <h1>index</h1>
    {% if user.is_authenticated %}
    <a href="{% url 'articles:create' %}" class="btn btn-secondary">write</a>
    {% endif %}
    {% for article in articles %}
    <div class="">
        <h3>{{ article.title }}</h3>
        <p>{{ article.user }}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>
    </div>
    <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'articles:index' %}">Home</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'articles:create' %}">Create</a>
                        <a class="nav-link" href="{% url 'accounts:logout' %}">Logout</a>
                        <a class="nav-link disabled" aria-disabled="true">{{ user }}</a>
                    {% else %}
                        <a class="nav-link" aria-current="page" href="{% url 'accounts:signup' %}">Signup</a>
                        <a class="nav-link" href="{% url 'accounts:login' %}">Login</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        {% block body %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>

</html>